# Generated by Django 4.2.8 on 2024-02-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_movie_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='added_by',
        ),
    ]
