# Generated by Django 4.2.8 on 2024-02-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0007_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
