# Generated by Django 4.2.8 on 2024-02-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0008_rename_text_review_comment_review_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
